process.env.MONGO_URL ||= "mongodb://localhost/x";
process.env.JWT_ACCESS_SECRET ||= "x";
process.env.JWT_REFRESH_SECRET ||= "x";
process.env.COOKIE_SECRET ||= "x";
process.env.TZ = "UTC";
const svc = await import("./src/modules/attendance/services/attendance.service.js");
await import("./src/jobs/index.js");
await import("./src/jobs/notificationDeliver.job.js");
console.assert(svc.computeRate({present:8,absent:2,excused:5,late:0,exempt:3})===80,"rate");
console.assert(typeof svc.consecutiveAbsences==="function","consec");
console.log("REVERIFY OK");
